### ISSUE TITLE
[Dev] 댓글 작성하는 기능 구현

### ISSUE THREAD

**Issue by tjdtls690** [dnd-side-project/dnd-10th-9-backend#20]
## Description

카드에 댓글을 작성할 수 있는 기능 구현

## Todo
- [x] 컨트롤러에서 API 작성 및 계층 구조 작성 (TDD)
- [x] 서비스 기능 구현
- [x] Swagger 명세 작성
- [x] 매일 자정에 TODAY_CARD 테이블을 리셋하도록 구현
- [x] 댓글 증가 동기화 처리
