### ISSUE TITLE
[Dev] 마이페이지 조회하기 기능 구현

### ISSUE THREAD

**Issue by tjdtls690** [dnd-side-project/dnd-10th-9-backend#27]
## Description

마이페이지 조회하기 기능 구현

## Todo
- [x] 컨트롤러에서 API 작성 및 계층 구조 작성
- [x] 서비스 기능 구현
- [x] Swagger 명세 작성
