### ISSUE TITLE
[Dev] 카드 삭제하기 기능 구현

### ISSUE THREAD

**Issue by tjdtls690** [dnd-side-project/dnd-10th-9-backend#34]
## Description

카드 삭제하기 기능 구현

## Todo
- [ ] 컨트롤러에서 API 작성 및 계층 구조 작성
- [ ] 서비스 기능 구현
- [ ] Swagger 명세 작성

## ETC
그 외
